(⎈ orv4prod:default) images [packer●] % packer build image.pkr.hcl
amazon-ebs.example: output will be in this color.

==> amazon-ebs.example: Prevalidating any provided VPC information
==> amazon-ebs.example: Prevalidating AMI Name: learn-terraform-packer-20210507184729
    amazon-ebs.example: Found Image ID: ami-04b2f7e61b9ca211f
==> amazon-ebs.example: Creating temporary keypair: packer_60958b42-2449-da31-a734-21c9e8e6e6be
==> amazon-ebs.example: Creating temporary security group for this instance: packer_60958b45-fc60-4c1f-5d18-7733c9b49961
==> amazon-ebs.example: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs.example: Launching a source AWS instance...
==> amazon-ebs.example: Adding tags to source instance
    amazon-ebs.example: Adding tag: "Name": "Packer Builder"
    amazon-ebs.example: Instance ID: i-0909c4b9264c42bf1
==> amazon-ebs.example: Waiting for instance (i-0909c4b9264c42bf1) to become ready...
==> amazon-ebs.example: Using ssh communicator to connect: 54.68.87.227
==> amazon-ebs.example: Waiting for SSH to become available...
==> amazon-ebs.example: Connected to SSH!
==> amazon-ebs.example: Uploading ../tf-packer.pub => /tmp/tf-packer.pub
    amazon-ebs.example: tf-packer.pub 575 B / 575 B [============================================================] 100.00% 0s
==> amazon-ebs.example: Provisioning with shell script: ../scripts/setup.sh
==> amazon-ebs.example: + sudo apt-get update -y
    amazon-ebs.example: Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
    amazon-ebs.example: Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
    amazon-ebs.example: Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
    amazon-ebs.example: Get:4 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [629 kB]
    amazon-ebs.example: Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
    amazon-ebs.example: Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]
    amazon-ebs.example: Get:7 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [128 kB]
    amazon-ebs.example: Get:8 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [7476 B]
    amazon-ebs.example: Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [558 kB]
    amazon-ebs.example: Get:10 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [84.1 kB]
    amazon-ebs.example: Get:11 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [10.8 kB]
    amazon-ebs.example: Get:12 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [14.9 kB]
    amazon-ebs.example: Get:13 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [3160 B]
    amazon-ebs.example: Get:14 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [340 B]
    amazon-ebs.example: Get:15 http://archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
    amazon-ebs.example: Get:16 http://archive.ubuntu.com/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]
    amazon-ebs.example: Get:17 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]
    amazon-ebs.example: Get:18 http://archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]
    amazon-ebs.example: Get:19 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]
    amazon-ebs.example: Get:20 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [955 kB]
    amazon-ebs.example: Get:21 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [218 kB]
    amazon-ebs.example: Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.2 kB]
    amazon-ebs.example: Get:23 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [768 kB]
    amazon-ebs.example: Get:24 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [165 kB]
    amazon-ebs.example: Get:25 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [17.2 kB]
    amazon-ebs.example: Get:26 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.7 kB]
    amazon-ebs.example: Get:27 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [5508 B]
    amazon-ebs.example: Get:28 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [600 B]
    amazon-ebs.example: Get:29 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [112 B]
    amazon-ebs.example: Get:30 http://archive.ubuntu.com/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Get:31 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4032 B]
    amazon-ebs.example: Get:32 http://archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [1448 B]
    amazon-ebs.example: Get:33 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [224 B]
    amazon-ebs.example: Get:34 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Fetched 18.2 MB in 7s (2588 kB/s)
==> amazon-ebs.example: Traceback (most recent call last):
==> amazon-ebs.example:   File "/usr/lib/cnf-update-db", line 26, in <module>
==> amazon-ebs.example:     col.create(db)
==> amazon-ebs.example:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 94, in create
==> amazon-ebs.example:     self._fill_commands(con)
==> amazon-ebs.example:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 137, in _fill_commands
==> amazon-ebs.example:     with open(f) as fp:
==> amazon-ebs.example: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal_multiverse_cnf_Commands-amd64'
    amazon-ebs.example: Reading package lists...
==> amazon-ebs.example: E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
==> amazon-ebs.example: E: Sub-process returned an error code
==> amazon-ebs.example: + sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold dist-upgrade
    amazon-ebs.example: Reading package lists...
    amazon-ebs.example: Building dependency tree...
    amazon-ebs.example: Reading state information...
    amazon-ebs.example: Calculating upgrade...
    amazon-ebs.example: The following packages will be upgraded:
    amazon-ebs.example:   alsa-ucm-conf apport libasound2 libasound2-data libxmlb1 open-iscsi
    amazon-ebs.example:   open-vm-tools python3-apport python3-problem-report python3-update-manager
    amazon-ebs.example:   tmux update-manager-core
    amazon-ebs.example: 12 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    amazon-ebs.example: Need to get 1883 kB of archives.
    amazon-ebs.example: After this operation, 509 kB of additional disk space will be used.
    amazon-ebs.example: Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 open-iscsi amd64 2.0.874-7.1ubuntu6.2 [283 kB]
    amazon-ebs.example: Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-update-manager all 1:20.04.10.7 [38.2 kB]
    amazon-ebs.example: Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 update-manager-core all 1:20.04.10.7 [11.3 kB]
    amazon-ebs.example: Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libasound2 amd64 1.2.2-2.1ubuntu2.4 [334 kB]
    amazon-ebs.example: Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libasound2-data all 1.2.2-2.1ubuntu2.4 [20.0 kB]
    amazon-ebs.example: Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 alsa-ucm-conf all 1.2.2-1ubuntu0.7 [26.3 kB]
    amazon-ebs.example: Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-problem-report all 2.20.11-0ubuntu27.17 [9632 B]
    amazon-ebs.example: Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-apport all 2.20.11-0ubuntu27.17 [85.2 kB]
    amazon-ebs.example: Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 apport all 2.20.11-0ubuntu27.17 [129 kB]
    amazon-ebs.example: Get:10 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 libxmlb1 amd64 0.1.15-2ubuntu1~20.04.1 [50.5 kB]
    amazon-ebs.example: Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 tmux amd64 3.0a-2ubuntu0.3 [292 kB]
    amazon-ebs.example: Get:12 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 open-vm-tools amd64 2:11.2.5-2ubuntu1~ubuntu20.04.1 [604 kB]
    amazon-ebs.example: Preconfiguring packages ...
    amazon-ebs.example: Fetched 1883 kB in 0s (33.2 MB/s)
    amazon-ebs.example: (Reading database ... 60149 files and directories currently installed.)
    amazon-ebs.example: Preparing to unpack .../00-open-iscsi_2.0.874-7.1ubuntu6.2_amd64.deb ...
    amazon-ebs.example: Unpacking open-iscsi (2.0.874-7.1ubuntu6.2) over (2.0.874-7.1ubuntu6.1) ...
    amazon-ebs.example: Preparing to unpack .../01-python3-update-manager_1%3a20.04.10.7_all.deb ...
    amazon-ebs.example: Unpacking python3-update-manager (1:20.04.10.7) over (1:20.04.10.6) ...
    amazon-ebs.example: Preparing to unpack .../02-update-manager-core_1%3a20.04.10.7_all.deb ...
    amazon-ebs.example: Unpacking update-manager-core (1:20.04.10.7) over (1:20.04.10.6) ...
    amazon-ebs.example: Preparing to unpack .../03-libasound2_1.2.2-2.1ubuntu2.4_amd64.deb ...
    amazon-ebs.example: Unpacking libasound2:amd64 (1.2.2-2.1ubuntu2.4) over (1.2.2-2.1ubuntu2.3) ...
    amazon-ebs.example: Preparing to unpack .../04-libasound2-data_1.2.2-2.1ubuntu2.4_all.deb ...
    amazon-ebs.example: Unpacking libasound2-data (1.2.2-2.1ubuntu2.4) over (1.2.2-2.1ubuntu2.3) ...
    amazon-ebs.example: Preparing to unpack .../05-alsa-ucm-conf_1.2.2-1ubuntu0.7_all.deb ...
    amazon-ebs.example: Unpacking alsa-ucm-conf (1.2.2-1ubuntu0.7) over (1.2.2-1ubuntu0.6) ...
    amazon-ebs.example: Preparing to unpack .../06-python3-problem-report_2.20.11-0ubuntu27.17_all.deb ...
    amazon-ebs.example: Unpacking python3-problem-report (2.20.11-0ubuntu27.17) over (2.20.11-0ubuntu27.16) ...
    amazon-ebs.example: Preparing to unpack .../07-python3-apport_2.20.11-0ubuntu27.17_all.deb ...
    amazon-ebs.example: Unpacking python3-apport (2.20.11-0ubuntu27.17) over (2.20.11-0ubuntu27.16) ...
    amazon-ebs.example: Preparing to unpack .../08-apport_2.20.11-0ubuntu27.17_all.deb ...
    amazon-ebs.example: Unpacking apport (2.20.11-0ubuntu27.17) over (2.20.11-0ubuntu27.16) ...
    amazon-ebs.example: Preparing to unpack .../09-libxmlb1_0.1.15-2ubuntu1~20.04.1_amd64.deb ...
    amazon-ebs.example: Unpacking libxmlb1:amd64 (0.1.15-2ubuntu1~20.04.1) over (0.1.15-2) ...
    amazon-ebs.example: Preparing to unpack .../10-tmux_3.0a-2ubuntu0.3_amd64.deb ...
    amazon-ebs.example: Unpacking tmux (3.0a-2ubuntu0.3) over (3.0a-2ubuntu0.2) ...
    amazon-ebs.example: Preparing to unpack .../11-open-vm-tools_2%3a11.2.5-2ubuntu1~ubuntu20.04.1_amd64.deb ...
    amazon-ebs.example: Unpacking open-vm-tools (2:11.2.5-2ubuntu1~ubuntu20.04.1) over (2:11.0.5-4) ...
    amazon-ebs.example: Setting up libxmlb1:amd64 (0.1.15-2ubuntu1~20.04.1) ...
    amazon-ebs.example: Setting up alsa-ucm-conf (1.2.2-1ubuntu0.7) ...
    amazon-ebs.example: Setting up python3-problem-report (2.20.11-0ubuntu27.17) ...
    amazon-ebs.example: Setting up open-iscsi (2.0.874-7.1ubuntu6.2) ...
    amazon-ebs.example: grep: /lib/modules-load.d/open-iscsi.conf: No such file or directory
    amazon-ebs.example: Setting up python3-apport (2.20.11-0ubuntu27.17) ...
    amazon-ebs.example: Setting up libasound2-data (1.2.2-2.1ubuntu2.4) ...
    amazon-ebs.example: Setting up open-vm-tools (2:11.2.5-2ubuntu1~ubuntu20.04.1) ...
    amazon-ebs.example: Installing new version of config file /etc/vmware-tools/tools.conf.example ...
    amazon-ebs.example: Installing new version of config file /etc/vmware-tools/vgauth.conf ...
    amazon-ebs.example: Setting up python3-update-manager (1:20.04.10.7) ...
    amazon-ebs.example: Setting up libasound2:amd64 (1.2.2-2.1ubuntu2.4) ...
    amazon-ebs.example: Setting up tmux (3.0a-2ubuntu0.3) ...
    amazon-ebs.example: Setting up apport (2.20.11-0ubuntu27.17) ...
    amazon-ebs.example: apport-autoreport.service is a disabled or a static unit, not starting it.
    amazon-ebs.example: Setting up update-manager-core (1:20.04.10.7) ...
    amazon-ebs.example: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Processing triggers for systemd (245.4-4ubuntu3.6) ...
    amazon-ebs.example: Processing triggers for man-db (2.9.1-1) ...
    amazon-ebs.example: Processing triggers for initramfs-tools (0.136ubuntu6.4) ...
    amazon-ebs.example: update-initramfs: Generating /boot/initrd.img-5.4.0-1047-aws
==> amazon-ebs.example: + sudo apt-get update
    amazon-ebs.example: Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
    amazon-ebs.example: Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
    amazon-ebs.example: Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
    amazon-ebs.example: Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
==> amazon-ebs.example: + sudo apt-get -y -qq install curl wget git vim apt-transport-https ca-certificates
    amazon-ebs.example: Reading package lists...
    amazon-ebs.example: Selecting previously unselected package apt-transport-https.
==> amazon-ebs.example: debconf: unable to initialize frontend: Dialog
==> amazon-ebs.example: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
==> amazon-ebs.example: debconf: falling back to frontend: Readline
==> amazon-ebs.example: debconf: unable to initialize frontend: Readline
==> amazon-ebs.example: debconf: (This frontend requires a controlling tty.)
==> amazon-ebs.example: debconf: falling back to frontend: Teletype
==> amazon-ebs.example: dpkg-preconfigure: unable to re-open stdin:
    amazon-ebs.example: (Reading database ... 60170 files and directories currently installed.)
    amazon-ebs.example: Preparing to unpack .../apt-transport-https_2.0.5_all.deb ...
    amazon-ebs.example: Unpacking apt-transport-https (2.0.5) ...
    amazon-ebs.example: Setting up apt-transport-https (2.0.5) ...
==> amazon-ebs.example: + sudo add-apt-repository ppa:longsleep/golang-backports -y
    amazon-ebs.example: Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
    amazon-ebs.example: Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
    amazon-ebs.example: Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
    amazon-ebs.example: Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
    amazon-ebs.example: Get:5 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease [17.5 kB]
    amazon-ebs.example: Get:6 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal/main amd64 Packages [2512 B]
    amazon-ebs.example: Get:7 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal/main Translation-en [1568 B]
    amazon-ebs.example: Fetched 21.6 kB in 1s (18.4 kB/s)
==> amazon-ebs.example: + sudo apt-get -y -qq install golang-go
    amazon-ebs.example: Reading package lists...
==> amazon-ebs.example: debconf: unable to initialize frontend: Dialog
==> amazon-ebs.example: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
==> amazon-ebs.example: debconf: falling back to frontend: Readline
==> amazon-ebs.example: debconf: unable to initialize frontend: Readline
==> amazon-ebs.example: debconf: (This frontend requires a controlling tty.)
==> amazon-ebs.example: debconf: falling back to frontend: Teletype
==> amazon-ebs.example: dpkg-preconfigure: unable to re-open stdin:
    amazon-ebs.example: Selecting previously unselected package binutils-common:amd64.
    amazon-ebs.example: (Reading database ... 60174 files and directories currently installed.)
    amazon-ebs.example: Preparing to unpack .../00-binutils-common_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils-common:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libbinutils:amd64.
    amazon-ebs.example: Preparing to unpack .../01-libbinutils_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libbinutils:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libctf-nobfd0:amd64.
    amazon-ebs.example: Preparing to unpack .../02-libctf-nobfd0_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libctf-nobfd0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libctf0:amd64.
    amazon-ebs.example: Preparing to unpack .../03-libctf0_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libctf0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package binutils-x86-64-linux-gnu.
    amazon-ebs.example: Preparing to unpack .../04-binutils-x86-64-linux-gnu_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils-x86-64-linux-gnu (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package binutils.
    amazon-ebs.example: Preparing to unpack .../05-binutils_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package gcc-9-base:amd64.
    amazon-ebs.example: Preparing to unpack .../06-gcc-9-base_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking gcc-9-base:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libisl22:amd64.
    amazon-ebs.example: Preparing to unpack .../07-libisl22_0.22.1-1_amd64.deb ...
    amazon-ebs.example: Unpacking libisl22:amd64 (0.22.1-1) ...
    amazon-ebs.example: Selecting previously unselected package libmpc3:amd64.
    amazon-ebs.example: Preparing to unpack .../08-libmpc3_1.1.0-1_amd64.deb ...
    amazon-ebs.example: Unpacking libmpc3:amd64 (1.1.0-1) ...
    amazon-ebs.example: Selecting previously unselected package cpp-9.
    amazon-ebs.example: Preparing to unpack .../09-cpp-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking cpp-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package cpp.
    amazon-ebs.example: Preparing to unpack .../10-cpp_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking cpp (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package libcc1-0:amd64.
    amazon-ebs.example: Preparing to unpack .../11-libcc1-0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libcc1-0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libgomp1:amd64.
    amazon-ebs.example: Preparing to unpack .../12-libgomp1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libgomp1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libitm1:amd64.
    amazon-ebs.example: Preparing to unpack .../13-libitm1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libitm1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libatomic1:amd64.
    amazon-ebs.example: Preparing to unpack .../14-libatomic1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libatomic1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libasan5:amd64.
    amazon-ebs.example: Preparing to unpack .../15-libasan5_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libasan5:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package liblsan0:amd64.
    amazon-ebs.example: Preparing to unpack .../16-liblsan0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking liblsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libtsan0:amd64.
    amazon-ebs.example: Preparing to unpack .../17-libtsan0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libtsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libubsan1:amd64.
    amazon-ebs.example: Preparing to unpack .../18-libubsan1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libubsan1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libquadmath0:amd64.
    amazon-ebs.example: Preparing to unpack .../19-libquadmath0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libquadmath0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libgcc-9-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../20-libgcc-9-dev_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libgcc-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package gcc-9.
    amazon-ebs.example: Preparing to unpack .../21-gcc-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking gcc-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package gcc.
    amazon-ebs.example: Preparing to unpack .../22-gcc_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking gcc (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package libc-dev-bin.
    amazon-ebs.example: Preparing to unpack .../23-libc-dev-bin_2.31-0ubuntu9.2_amd64.deb ...
    amazon-ebs.example: Unpacking libc-dev-bin (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Selecting previously unselected package linux-libc-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../24-linux-libc-dev_5.4.0-72.80_amd64.deb ...
    amazon-ebs.example: Unpacking linux-libc-dev:amd64 (5.4.0-72.80) ...
    amazon-ebs.example: Selecting previously unselected package libcrypt-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../25-libcrypt-dev_1%3a4.4.10-10ubuntu4_amd64.deb ...
    amazon-ebs.example: Unpacking libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
    amazon-ebs.example: Selecting previously unselected package libc6-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../26-libc6-dev_2.31-0ubuntu9.2_amd64.deb ...
    amazon-ebs.example: Unpacking libc6-dev:amd64 (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Selecting previously unselected package libstdc++-9-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../27-libstdc++-9-dev_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libstdc++-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package g++-9.
    amazon-ebs.example: Preparing to unpack .../28-g++-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking g++-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package g++.
    amazon-ebs.example: Preparing to unpack .../29-g++_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking g++ (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package golang-1.16-src.
    amazon-ebs.example: Preparing to unpack .../30-golang-1.16-src_1.16.4-1longsleep1+focal_amd64.deb ...
    amazon-ebs.example: Unpacking golang-1.16-src (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Selecting previously unselected package golang-1.16-go.
    amazon-ebs.example: Preparing to unpack .../31-golang-1.16-go_1.16.4-1longsleep1+focal_amd64.deb ...
    amazon-ebs.example: Unpacking golang-1.16-go (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Selecting previously unselected package golang-src.
    amazon-ebs.example: Preparing to unpack .../32-golang-src_2%3a1.16-1longsleep1+bionic_amd64.deb ...
    amazon-ebs.example: Unpacking golang-src (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Selecting previously unselected package golang-go.
    amazon-ebs.example: Preparing to unpack .../33-golang-go_2%3a1.16-1longsleep1+bionic_amd64.deb ...
    amazon-ebs.example: Unpacking golang-go (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Selecting previously unselected package libdpkg-perl.
    amazon-ebs.example: Preparing to unpack .../34-libdpkg-perl_1.19.7ubuntu3_all.deb ...
    amazon-ebs.example: Unpacking libdpkg-perl (1.19.7ubuntu3) ...
    amazon-ebs.example: Selecting previously unselected package libfile-fcntllock-perl.
    amazon-ebs.example: Preparing to unpack .../35-libfile-fcntllock-perl_0.22-3build4_amd64.deb ...
    amazon-ebs.example: Unpacking libfile-fcntllock-perl (0.22-3build4) ...
    amazon-ebs.example: Selecting previously unselected package manpages-dev.
    amazon-ebs.example: Preparing to unpack .../36-manpages-dev_5.05-1_all.deb ...
    amazon-ebs.example: Unpacking manpages-dev (5.05-1) ...
    amazon-ebs.example: Selecting previously unselected package pkg-config.
    amazon-ebs.example: Preparing to unpack .../37-pkg-config_0.29.1-0ubuntu4_amd64.deb ...
    amazon-ebs.example: Unpacking pkg-config (0.29.1-0ubuntu4) ...
    amazon-ebs.example: Setting up manpages-dev (5.05-1) ...
    amazon-ebs.example: Setting up libfile-fcntllock-perl (0.22-3build4) ...
    amazon-ebs.example: Setting up binutils-common:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up linux-libc-dev:amd64 (5.4.0-72.80) ...
    amazon-ebs.example: Setting up libctf-nobfd0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libgomp1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up golang-1.16-src (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Setting up libquadmath0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libmpc3:amd64 (1.1.0-1) ...
    amazon-ebs.example: Setting up libatomic1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libdpkg-perl (1.19.7ubuntu3) ...
    amazon-ebs.example: Setting up libubsan1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
    amazon-ebs.example: Setting up libisl22:amd64 (0.22.1-1) ...
    amazon-ebs.example: Setting up libbinutils:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libc-dev-bin (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Setting up golang-src (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Setting up libcc1-0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up liblsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libitm1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up gcc-9-base:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libtsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libctf0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up golang-1.16-go (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Setting up libasan5:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up pkg-config (0.29.1-0ubuntu4) ...
    amazon-ebs.example: Setting up cpp-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libc6-dev:amd64 (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Setting up binutils-x86-64-linux-gnu (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up golang-go (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Setting up binutils (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libgcc-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up cpp (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Setting up gcc-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libstdc++-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up gcc (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Setting up g++-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up g++ (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
    amazon-ebs.example: Processing triggers for man-db (2.9.1-1) ...
    amazon-ebs.example: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
==> amazon-ebs.example: + sudo groupadd -r hashicorp
==> amazon-ebs.example: + sudo useradd -m -s /bin/bash terraform
==> amazon-ebs.example: + sudo usermod -a -G hashicorp terraform
==> amazon-ebs.example: + sudo cp /etc/sudoers /etc/sudoers.orig
==> amazon-ebs.example: + sudo tee /etc/sudoers.d/terraform
==> amazon-ebs.example: + echo 'terraform  ALL=(ALL) NOPASSWD:ALL'
==> amazon-ebs.example: + sudo mkdir -p /home/terraform/.ssh
    amazon-ebs.example: terraform  ALL=(ALL) NOPASSWD:ALL
==> amazon-ebs.example: + sudo chmod 700 /home/terraform/.ssh
==> amazon-ebs.example: + sudo cp /tmp/tf-packer.pub /home/terraform/.ssh/authorized_keys
==> amazon-ebs.example: + sudo chmod 600 /home/terraform/.ssh/authorized_keys
==> amazon-ebs.example: + sudo chown -R terraform /home/terraform/.ssh
    amazon-ebs.example: usermod: no changes
==> amazon-ebs.example: + sudo usermod --shell /bin/bash terraform
==> amazon-ebs.example: + sudo -H -i -u terraform -- env bash
    amazon-ebs.example: terraform
    amazon-ebs.example: /home/terraform
==> amazon-ebs.example: go: downloading github.com/hashicorp/learn-go-webapp-demo v0.0.0-20200715024259-8f1f7d755351
==> amazon-ebs.example: Stopping the source instance...
    amazon-ebs.example: Stopping instance
==> amazon-ebs.example: Waiting for the instance to stop...
==> amazon-ebs.example: Creating AMI learn-terraform-packer-20210507184729 from instance i-0909c4b9264c42bf1
    amazon-ebs.example: AMI: ami-07e9f9c3f5ac3dfb9
==> amazon-ebs.example: Waiting for AMI to become ready...
==> amazon-ebs.example: Terminating the source AWS instance...
==> amazon-ebs.example: Cleaning up any extra volumes...
==> amazon-ebs.example: No volumes to clean up, skipping
==> amazon-ebs.example: Deleting temporary security group...
==> amazon-ebs.example: Deleting temporary keypair...
Build 'amazon-ebs.example' finished after 6 minutes 28 seconds.

==> Wait completed after 6 minutes 28 seconds

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs.example: AMIs were created:
us-west-2: ami-07e9f9c3f5ac3dfb9

(⎈ orv4prod:default) images [packer●] %
(⎈ orv4prod:default) images [packer●] %
(⎈ orv4prod:default) images [packer●] % packer build image.pkr.hcl 2>&1 | tee output.txt
amazon-ebs.example: output will be in this color.

==> amazon-ebs.example: Prevalidating any provided VPC information
==> amazon-ebs.example: Prevalidating AMI Name: learn-terraform-packer-20210507190235
    amazon-ebs.example: Found Image ID: ami-04b2f7e61b9ca211f
==> amazon-ebs.example: Creating temporary keypair: packer_60958ecb-4247-feb2-ebc8-8bb52621bf57
==> amazon-ebs.example: Creating temporary security group for this instance: packer_60958ece-eecb-210b-3811-8e8f07cc5619
==> amazon-ebs.example: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs.example: Launching a source AWS instance...
==> amazon-ebs.example: Adding tags to source instance
    amazon-ebs.example: Adding tag: "Name": "Packer Builder"
    amazon-ebs.example: Instance ID: i-088478da237e23d3d
==> amazon-ebs.example: Waiting for instance (i-088478da237e23d3d) to become ready...
==> amazon-ebs.example: Using ssh communicator to connect: 34.209.151.198
==> amazon-ebs.example: Waiting for SSH to become available...
==> amazon-ebs.example: Connected to SSH!
==> amazon-ebs.example: Uploading ../tf-packer.pub => /tmp/tf-packer.pub
    amazon-ebs.example: tf-packer.pub 575 B / 575 B [============================================================] 100.00% 0s
==> amazon-ebs.example: Provisioning with shell script: ../scripts/setup.sh
==> amazon-ebs.example: + sudo apt-get update -y
    amazon-ebs.example: Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
    amazon-ebs.example: Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
    amazon-ebs.example: Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
    amazon-ebs.example: Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
    amazon-ebs.example: Get:5 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [629 kB]
    amazon-ebs.example: Get:6 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [128 kB]
    amazon-ebs.example: Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [7476 B]
    amazon-ebs.example: Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [558 kB]
    amazon-ebs.example: Get:9 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]
    amazon-ebs.example: Get:10 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [84.1 kB]
    amazon-ebs.example: Get:11 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [10.8 kB]
    amazon-ebs.example: Get:12 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [14.9 kB]
    amazon-ebs.example: Get:13 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [3160 B]
    amazon-ebs.example: Get:14 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [340 B]
    amazon-ebs.example: Get:15 http://archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
    amazon-ebs.example: Get:16 http://archive.ubuntu.com/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]
    amazon-ebs.example: Get:17 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]
    amazon-ebs.example: Get:18 http://archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]
    amazon-ebs.example: Get:19 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]
    amazon-ebs.example: Get:20 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [955 kB]
    amazon-ebs.example: Get:21 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [218 kB]
    amazon-ebs.example: Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.2 kB]
    amazon-ebs.example: Get:23 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [768 kB]
    amazon-ebs.example: Get:24 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [165 kB]
    amazon-ebs.example: Get:25 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [17.2 kB]
    amazon-ebs.example: Get:26 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.7 kB]
    amazon-ebs.example: Get:27 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [5508 B]
    amazon-ebs.example: Get:28 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [600 B]
    amazon-ebs.example: Get:29 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [112 B]
    amazon-ebs.example: Get:30 http://archive.ubuntu.com/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Get:31 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4032 B]
    amazon-ebs.example: Get:32 http://archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [1448 B]
    amazon-ebs.example: Get:33 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [224 B]
    amazon-ebs.example: Get:34 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Fetched 18.2 MB in 5s (3320 kB/s)
==> amazon-ebs.example: + sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold dist-upgrade
    amazon-ebs.example: Reading package lists...
    amazon-ebs.example: Reading package lists...
    amazon-ebs.example: Building dependency tree...
    amazon-ebs.example: Reading state information...
    amazon-ebs.example: Calculating upgrade...
==> amazon-ebs.example: + sudo apt-get update
    amazon-ebs.example: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    amazon-ebs.example: Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease [265 kB]
    amazon-ebs.example: Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
    amazon-ebs.example: Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
    amazon-ebs.example: Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 Packages [970 kB]
    amazon-ebs.example: Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
    amazon-ebs.example: Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main Translation-en [506 kB]
    amazon-ebs.example: Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 c-n-f Metadata [29.5 kB]
    amazon-ebs.example: Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [22.0 kB]
    amazon-ebs.example: Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/restricted Translation-en [6212 B]
    amazon-ebs.example: Get:10 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/restricted amd64 c-n-f Metadata [392 B]
    amazon-ebs.example: Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 Packages [8628 kB]
    amazon-ebs.example: Get:12 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe Translation-en [5124 kB]
    amazon-ebs.example: Get:13 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 c-n-f Metadata [265 kB]
    amazon-ebs.example: Get:14 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [144 kB]
    amazon-ebs.example: Get:15 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/multiverse Translation-en [104 kB]
    amazon-ebs.example: Get:16 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/multiverse amd64 c-n-f Metadata [9136 B]
    amazon-ebs.example: Get:17 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [955 kB]
    amazon-ebs.example: Get:18 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [218 kB]
    amazon-ebs.example: Get:19 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.2 kB]
    amazon-ebs.example: Get:20 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [208 kB]
    amazon-ebs.example: Get:21 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [30.9 kB]
    amazon-ebs.example: Get:22 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [436 B]
    amazon-ebs.example: Get:23 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [768 kB]
    amazon-ebs.example: Get:24 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [165 kB]
    amazon-ebs.example: Get:25 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [17.2 kB]
    amazon-ebs.example: Get:26 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.7 kB]
    amazon-ebs.example: Get:27 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [5508 B]
    amazon-ebs.example: Get:28 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [600 B]
    amazon-ebs.example: Get:29 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [112 B]
    amazon-ebs.example: Get:30 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/restricted amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Get:31 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4032 B]
    amazon-ebs.example: Get:32 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [1448 B]
    amazon-ebs.example: Get:33 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [224 B]
    amazon-ebs.example: Get:34 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]
    amazon-ebs.example: Fetched 18.7 MB in 3s (5968 kB/s)
    amazon-ebs.example: Reading package lists...
==> amazon-ebs.example: + sudo apt-get -y -qq install curl wget git vim apt-transport-https ca-certificates
==> amazon-ebs.example: debconf: unable to initialize frontend: Dialog
==> amazon-ebs.example: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
==> amazon-ebs.example: debconf: falling back to frontend: Readline
==> amazon-ebs.example: debconf: unable to initialize frontend: Readline
==> amazon-ebs.example: debconf: (This frontend requires a controlling tty.)
==> amazon-ebs.example: debconf: falling back to frontend: Teletype
==> amazon-ebs.example: dpkg-preconfigure: unable to re-open stdin:
    amazon-ebs.example: Selecting previously unselected package apt-transport-https.
    amazon-ebs.example: (Reading database ... 60149 files and directories currently installed.)
    amazon-ebs.example: Preparing to unpack .../apt-transport-https_2.0.5_all.deb ...
    amazon-ebs.example: Unpacking apt-transport-https (2.0.5) ...
    amazon-ebs.example: Setting up apt-transport-https (2.0.5) ...
==> amazon-ebs.example: + sudo add-apt-repository ppa:longsleep/golang-backports -y
    amazon-ebs.example: Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
    amazon-ebs.example: Hit:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease
    amazon-ebs.example: Hit:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease
    amazon-ebs.example: Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
    amazon-ebs.example: Get:5 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease [17.5 kB]
    amazon-ebs.example: Get:6 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal/main amd64 Packages [2512 B]
    amazon-ebs.example: Get:7 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal/main Translation-en [1568 B]
    amazon-ebs.example: Fetched 21.6 kB in 4s (5334 B/s)
    amazon-ebs.example: Reading package lists...
==> amazon-ebs.example: + sudo apt-get -y -qq install golang-go
==> amazon-ebs.example: debconf: unable to initialize frontend: Dialog
==> amazon-ebs.example: debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
==> amazon-ebs.example: debconf: falling back to frontend: Readline
==> amazon-ebs.example: debconf: unable to initialize frontend: Readline
==> amazon-ebs.example: debconf: (This frontend requires a controlling tty.)
==> amazon-ebs.example: debconf: falling back to frontend: Teletype
==> amazon-ebs.example: dpkg-preconfigure: unable to re-open stdin:
    amazon-ebs.example: Selecting previously unselected package binutils-common:amd64.
    amazon-ebs.example: (Reading database ... 60153 files and directories currently installed.)
    amazon-ebs.example: Preparing to unpack .../00-binutils-common_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils-common:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libbinutils:amd64.
    amazon-ebs.example: Preparing to unpack .../01-libbinutils_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libbinutils:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libctf-nobfd0:amd64.
    amazon-ebs.example: Preparing to unpack .../02-libctf-nobfd0_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libctf-nobfd0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package libctf0:amd64.
    amazon-ebs.example: Preparing to unpack .../03-libctf0_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking libctf0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package binutils-x86-64-linux-gnu.
    amazon-ebs.example: Preparing to unpack .../04-binutils-x86-64-linux-gnu_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils-x86-64-linux-gnu (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package binutils.
    amazon-ebs.example: Preparing to unpack .../05-binutils_2.34-6ubuntu1.1_amd64.deb ...
    amazon-ebs.example: Unpacking binutils (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Selecting previously unselected package gcc-9-base:amd64.
    amazon-ebs.example: Preparing to unpack .../06-gcc-9-base_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking gcc-9-base:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libisl22:amd64.
    amazon-ebs.example: Preparing to unpack .../07-libisl22_0.22.1-1_amd64.deb ...
    amazon-ebs.example: Unpacking libisl22:amd64 (0.22.1-1) ...
    amazon-ebs.example: Selecting previously unselected package libmpc3:amd64.
    amazon-ebs.example: Preparing to unpack .../08-libmpc3_1.1.0-1_amd64.deb ...
    amazon-ebs.example: Unpacking libmpc3:amd64 (1.1.0-1) ...
    amazon-ebs.example: Selecting previously unselected package cpp-9.
    amazon-ebs.example: Preparing to unpack .../09-cpp-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking cpp-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package cpp.
    amazon-ebs.example: Preparing to unpack .../10-cpp_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking cpp (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package libcc1-0:amd64.
    amazon-ebs.example: Preparing to unpack .../11-libcc1-0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libcc1-0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libgomp1:amd64.
    amazon-ebs.example: Preparing to unpack .../12-libgomp1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libgomp1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libitm1:amd64.
    amazon-ebs.example: Preparing to unpack .../13-libitm1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libitm1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libatomic1:amd64.
    amazon-ebs.example: Preparing to unpack .../14-libatomic1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libatomic1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libasan5:amd64.
    amazon-ebs.example: Preparing to unpack .../15-libasan5_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libasan5:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package liblsan0:amd64.
    amazon-ebs.example: Preparing to unpack .../16-liblsan0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking liblsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libtsan0:amd64.
    amazon-ebs.example: Preparing to unpack .../17-libtsan0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libtsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libubsan1:amd64.
    amazon-ebs.example: Preparing to unpack .../18-libubsan1_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libubsan1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libquadmath0:amd64.
    amazon-ebs.example: Preparing to unpack .../19-libquadmath0_10.2.0-5ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libquadmath0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package libgcc-9-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../20-libgcc-9-dev_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libgcc-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package gcc-9.
    amazon-ebs.example: Preparing to unpack .../21-gcc-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking gcc-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package gcc.
    amazon-ebs.example: Preparing to unpack .../22-gcc_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking gcc (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package libc-dev-bin.
    amazon-ebs.example: Preparing to unpack .../23-libc-dev-bin_2.31-0ubuntu9.2_amd64.deb ...
    amazon-ebs.example: Unpacking libc-dev-bin (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Selecting previously unselected package linux-libc-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../24-linux-libc-dev_5.4.0-72.80_amd64.deb ...
    amazon-ebs.example: Unpacking linux-libc-dev:amd64 (5.4.0-72.80) ...
    amazon-ebs.example: Selecting previously unselected package libcrypt-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../25-libcrypt-dev_1%3a4.4.10-10ubuntu4_amd64.deb ...
    amazon-ebs.example: Unpacking libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
    amazon-ebs.example: Selecting previously unselected package libc6-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../26-libc6-dev_2.31-0ubuntu9.2_amd64.deb ...
    amazon-ebs.example: Unpacking libc6-dev:amd64 (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Selecting previously unselected package libstdc++-9-dev:amd64.
    amazon-ebs.example: Preparing to unpack .../27-libstdc++-9-dev_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking libstdc++-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package g++-9.
    amazon-ebs.example: Preparing to unpack .../28-g++-9_9.3.0-17ubuntu1~20.04_amd64.deb ...
    amazon-ebs.example: Unpacking g++-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Selecting previously unselected package g++.
    amazon-ebs.example: Preparing to unpack .../29-g++_4%3a9.3.0-1ubuntu2_amd64.deb ...
    amazon-ebs.example: Unpacking g++ (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Selecting previously unselected package golang-1.16-src.
    amazon-ebs.example: Preparing to unpack .../30-golang-1.16-src_1.16.4-1longsleep1+focal_amd64.deb ...
    amazon-ebs.example: Unpacking golang-1.16-src (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Selecting previously unselected package golang-1.16-go.
    amazon-ebs.example: Preparing to unpack .../31-golang-1.16-go_1.16.4-1longsleep1+focal_amd64.deb ...
    amazon-ebs.example: Unpacking golang-1.16-go (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Selecting previously unselected package golang-src.
    amazon-ebs.example: Preparing to unpack .../32-golang-src_2%3a1.16-1longsleep1+bionic_amd64.deb ...
    amazon-ebs.example: Unpacking golang-src (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Selecting previously unselected package golang-go.
    amazon-ebs.example: Preparing to unpack .../33-golang-go_2%3a1.16-1longsleep1+bionic_amd64.deb ...
    amazon-ebs.example: Unpacking golang-go (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Selecting previously unselected package libdpkg-perl.
    amazon-ebs.example: Preparing to unpack .../34-libdpkg-perl_1.19.7ubuntu3_all.deb ...
    amazon-ebs.example: Unpacking libdpkg-perl (1.19.7ubuntu3) ...
    amazon-ebs.example: Selecting previously unselected package libfile-fcntllock-perl.
    amazon-ebs.example: Preparing to unpack .../35-libfile-fcntllock-perl_0.22-3build4_amd64.deb ...
    amazon-ebs.example: Unpacking libfile-fcntllock-perl (0.22-3build4) ...
    amazon-ebs.example: Selecting previously unselected package manpages-dev.
    amazon-ebs.example: Preparing to unpack .../36-manpages-dev_5.05-1_all.deb ...
    amazon-ebs.example: Unpacking manpages-dev (5.05-1) ...
    amazon-ebs.example: Selecting previously unselected package pkg-config.
    amazon-ebs.example: Preparing to unpack .../37-pkg-config_0.29.1-0ubuntu4_amd64.deb ...
    amazon-ebs.example: Unpacking pkg-config (0.29.1-0ubuntu4) ...
    amazon-ebs.example: Setting up manpages-dev (5.05-1) ...
    amazon-ebs.example: Setting up libfile-fcntllock-perl (0.22-3build4) ...
    amazon-ebs.example: Setting up binutils-common:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up linux-libc-dev:amd64 (5.4.0-72.80) ...
    amazon-ebs.example: Setting up libctf-nobfd0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libgomp1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up golang-1.16-src (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Setting up libquadmath0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libmpc3:amd64 (1.1.0-1) ...
    amazon-ebs.example: Setting up libatomic1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libdpkg-perl (1.19.7ubuntu3) ...
    amazon-ebs.example: Setting up libubsan1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
    amazon-ebs.example: Setting up libisl22:amd64 (0.22.1-1) ...
    amazon-ebs.example: Setting up libbinutils:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libc-dev-bin (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Setting up golang-src (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Setting up libcc1-0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up liblsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libitm1:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up gcc-9-base:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libtsan0:amd64 (10.2.0-5ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libctf0:amd64 (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up golang-1.16-go (1.16.4-1longsleep1+focal) ...
    amazon-ebs.example: Setting up libasan5:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up pkg-config (0.29.1-0ubuntu4) ...
    amazon-ebs.example: Setting up cpp-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libc6-dev:amd64 (2.31-0ubuntu9.2) ...
    amazon-ebs.example: Setting up binutils-x86-64-linux-gnu (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up golang-go (2:1.16-1longsleep1+bionic) ...
    amazon-ebs.example: Setting up binutils (2.34-6ubuntu1.1) ...
    amazon-ebs.example: Setting up libgcc-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up cpp (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Setting up gcc-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up libstdc++-9-dev:amd64 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up gcc (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: Setting up g++-9 (9.3.0-17ubuntu1~20.04) ...
    amazon-ebs.example: Setting up g++ (4:9.3.0-1ubuntu2) ...
    amazon-ebs.example: update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
    amazon-ebs.example: Processing triggers for man-db (2.9.1-1) ...
    amazon-ebs.example: Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
==> amazon-ebs.example: + sudo groupadd -r hashicorp
==> amazon-ebs.example: + sudo useradd -m -s /bin/bash terraform
==> amazon-ebs.example: + sudo usermod -a -G hashicorp terraform
==> amazon-ebs.example: + sudo cp /etc/sudoers /etc/sudoers.orig
==> amazon-ebs.example: + sudo tee /etc/sudoers.d/terraform
==> amazon-ebs.example: + echo 'terraform  ALL=(ALL) NOPASSWD:ALL'
    amazon-ebs.example: terraform  ALL=(ALL) NOPASSWD:ALL
==> amazon-ebs.example: + sudo mkdir -p /home/terraform/.ssh
==> amazon-ebs.example: + sudo chmod 700 /home/terraform/.ssh
==> amazon-ebs.example: + sudo cp /tmp/tf-packer.pub /home/terraform/.ssh/authorized_keys
==> amazon-ebs.example: + sudo chmod 600 /home/terraform/.ssh/authorized_keys
==> amazon-ebs.example: + sudo chown -R terraform /home/terraform/.ssh
==> amazon-ebs.example: + sudo usermod --shell /bin/bash terraform
    amazon-ebs.example: usermod: no changes
==> amazon-ebs.example: + sudo -H -i -u terraform -- env bash
    amazon-ebs.example: terraform
    amazon-ebs.example: /home/terraform
==> amazon-ebs.example: go: downloading github.com/hashicorp/learn-go-webapp-demo v0.0.0-20200715024259-8f1f7d755351
==> amazon-ebs.example: Stopping the source instance...
    amazon-ebs.example: Stopping instance
==> amazon-ebs.example: Waiting for the instance to stop...
==> amazon-ebs.example: Creating AMI learn-terraform-packer-20210507190235 from instance i-088478da237e23d3d
    amazon-ebs.example: AMI: ami-000fc65b04ce59407
==> amazon-ebs.example: Waiting for AMI to become ready...
==> amazon-ebs.example: Terminating the source AWS instance...
==> amazon-ebs.example: Cleaning up any extra volumes...
==> amazon-ebs.example: No volumes to clean up, skipping
==> amazon-ebs.example: Deleting temporary security group...
==> amazon-ebs.example: Deleting temporary keypair...
Build 'amazon-ebs.example' finished after 9 minutes 57 seconds.

==> Wait completed after 9 minutes 57 seconds

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs.example: AMIs were created:
us-west-2: ami-000fc65b04ce59407

(⎈ orv4prod:default) images [packer●●] % tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' > sudo ami.txt
awk: can't open file ami.txt
 source line number 1
(⎈ orv4prod:default) images [packer●●] % tail -2 output.txt
us-west-2: ami-000fc65b04ce59407

(⎈ orv4prod:default) images [packer●●] % tail -2 output.txt | head -2
us-west-2: ami-000fc65b04ce59407

(⎈ orv4prod:default) images [packer●●] % tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }' > ami.txt
(⎈ orv4prod:default) images [packer●●] % cat ami.txt
ami-000fc65b04ce59407
(⎈ orv4prod:default) images [packer●●] % rm ami.txt
(⎈ orv4prod:default) images [packer●●] % AMI=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }') echo 'locals {\n  newami = "${AMI}"\n}' > packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % vi packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % rm packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % AMI=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }') echo $AMI

(⎈ orv4prod:default) images [packer●●] % AMI=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }')
(⎈ orv4prod:default) images [packer●●] % echo $AMI
ami-000fc65b04ce59407
(⎈ orv4prod:default) images [packer●●] % unset AMI
(⎈ orv4prod:default) images [packer●●] % AMI=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }') && echo 'locals {\n  new_ami = "${AMI}"\n}' > packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % cat packer-locals.tf
locals {
  new_ami = "${AMI}"
}
(⎈ orv4prod:default) images [packer●●] % rm packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % AMI=$(tail -2 output.txt | head -2 | awk 'match($0, /ami-.*/) { print substr($0, RSTART, RLENGTH) }') && echo 'locals {\n  new_ami = "' > packer-locals.tf && echo ${AMI} >>packer-locals.tf && echo '"\n}'
"
}
(⎈ orv4prod:default) images [packer●●] % cat packer-locals.tf
locals {
  new_ami = "
ami-000fc65b04ce59407
(⎈ orv4prod:default) images [packer●●] % PREFIX='locals {\n  new_api = "'
(⎈ orv4prod:default) images [packer●●] % SUFFIX='"}'
(⎈ orv4prod:default) images [packer●●] % echo "${PREFIX}${AMI}${SUFFIX}"
locals {
  new_api = "ami-000fc65b04ce59407"}
(⎈ orv4prod:default) images [packer●●] % SUFFIX='"\n}'
(⎈ orv4prod:default) images [packer●●] % echo "${PREFIX}${AMI}${SUFFIX}"
locals {
  new_api = "ami-000fc65b04ce59407"
}
(⎈ orv4prod:default) images [packer●●] % echo "${PREFIX}${AMI}${SUFFIX}" > packer-locals.tf
(⎈ orv4prod:default) images [packer●●] % cat packer-locals.tf
locals {
  new_api = "ami-000fc65b04ce59407"
}
